name: Build and Test

on:
  pull_request: {}
  push: { branches: [master] }

jobs:
  buildAndTest:
    name: Build and test (2019.3.11f1)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v1.1.0
        with:
          path: test-project-2019.3/Library
          key: Library-test-project-2019.3-${{ github.sha }}
          restore-keys: |
            Library-test-project-2019.3-
            Library-

      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          projectPath: test-project-2019.3
          unityVersion: 2019.3.11f1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2019_3 }}

      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          projectPath: test-project-2019.3
          unityVersion: 2019.3.11f1
          targetPlatform: WebGL
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2019_3 }}
